### ISSUE TITLE
Issue 45 - Compras - El campo Descripción está primero, cuando en todas las pantallas suele estar el producto.

### ISSUE THREAD

**Issue by sebatista** [jobiols/cl-amic#133]
En la pantalla de Remitos de una purchase order (PO) la columna de producto, donde se debe indicar el código está en segundo lugar, luego de Descripción. Sería necesario invertirlo, ya que genera confusión.
![Descripción y producto están invertidos](https://user-images.githubusercontent.com/27778036/88544726-35cdc580-cff0-11ea-9c05-d05fc6c76604.jpg)

**Comment by jobiols** [comment]
Se invirtieron los campos solicitados, en el modulo customer_product_names
Se aplicaron los cambios en produccion.
