### ISSUE TITLE
Permisos y roles.

### ISSUE THREAD

**Issue by sebatista** [jobiols/cl-amic#141]
Se desea modificar los permisos de los usuarios, pero no se guardan los cambios realizados. 
Se utiliza el usuario admin para realizar ésta tarea. Tanto en la base de datos capacitación como producción.
Al modificar el perfil de "Contabilidad y Finanzas" a vacío, no se guardan los datos modificados para el usuario rvarela@amic.com.ar.
Se edita el registro, se indica el rol vacío y al guardar se vuelve a configurar con el rol Facturación.
Algo similar ocurre con el tilde de "Listas de precios de venta" y el tilde "Elegir Tipo de Pago en Pagos". Al guardar se vuelve a tildar la opción. Éste usuario no debe ver las listas de precios de ventas.

**Comment by jobiols** [comment]
Los permisos tienen herencia es decir que cierto por ejemplo, **Mostrar caracteristicas de contabilidad completas** agrega el perfil **Contabilidad y Finanzas** cosa que es razonable. (hay algunas cosas no tan claramente razonables ...)

La forma normal de agregar permisos es 
- Quitar todo dejando solamente el perfil de Empleado, que es el que le da la posibilidad de loguearse.
- Luego se van agregando los permisos necesarios de a uno.

**Notar:** que algunos tildes vuelven a aparecer porque heredan de caracteristicas instlaladas como ser el de administrar los numeros de lote.

Tambien es conveniente abrir dos ventanas de navegador (no orejas, dije ventanas) una en modo incognito con el admin y la otra con el usuario, se cambia un permiso y se refresca el usuario a ver si es lo que uno quiere.

Si asi y todo no se consigue hay que hacer un toque en los permisos.
