### ISSUE TITLE
Filtros por defecto

### ISSUE THREAD

**Issue by jobiols** [jobiols/cl-amic#144]
Definir un agrupamiento por defecto, para que se visualice como se muestra en la tabla dinámica lograda en excel, por defecto. 

Aclaré de donde sale el dato que estamos agrupando, para evitar diferencias entre los resultados de la exportación y de la tabla de pivot.

## Agrupamientos
- [x]  1er Agrupamiento por fila del Año de la Fecha Solicitada del pedido de venta.
- [x] 2do Agrupamiento por fila del Mes de la Fecha Solicitada del pedido de venta.
- [x] 3er Agrupamiento por fila del Almacén/Planta de la información de envío (Solapa otra información) del pedido de venta.
- [x] 4to Agrupamiento por fila del Nombre del cliente del pedido de venta.
- [x] 5to Agrupamiento por fila del Nombre mostrado del pedido de venta (SOXXX)
- [ ] 6to Agrupamiento por fila de la Acumulación de remitos relacionados con el pedido de venta. (Este campo merece una explicación, porque lo pidieron recientemente)
- [ ] 7mo Agrupamiento por fila de la Referencia interna del producto vendido en cada línea de pedido de venta.

## Medidas

- [x]  **Cantidad de Unidades Programadas** [programmed_units_qty] 1er Sumatoria por columna Campo Calculado Cantidad de piezas programadas. NOTA recordatoria: la cantidad de piezas programadas se necesita en unidades, no en cajas. Por ende éste campo es la multiplicación entre el ratio de la unidad de medida y la cantidad vendida de la línea del pedido de venta (por ejemplo si vendieron 10 cajas x 110, es 110 unidades por cada caja, es decir, 1100 unidades, y éste es el valor que debemos sumarizar aquí).
- [x] **Cantidad de Unidades Pendientes de Entrega** [pending_units_qty] 2da Sumatoria por columna del Campo Calculado Diferencia entre piezas programadas y piezas entregadas. Mismo razonamiento en cuanto a la unidad de medidas. Aquí debe figurar la sumatoria de la fórmula (Cantidad de cajas vendidas por la relación de la unidad de medida) - (Cantidad de cajas entregadas por la relación de la unidad de medida... Por ejemplo Vendí 10 cajas x 10 pero únicamente entregué 5 cajas x 10, entonces Vendí 100 piezas menos las 50 piezas que entregué, aquí debemos mostrar que faltan entregar 50 piezas).
- [x] **Cantidad de Unidades Despachadas** [dispatched_qty] 3er Sumatoria por columna del Campo Calculado Cantidad de piezas despachadas. Es la cantidad de cajas despachadas por la relación entre cajas y unidades, al igual que antes, pero sobre las cantidades entregadas.
- [x] **Facturación USD** [invoiced_usd] 4ta Sumatoria por columna del Campo Calculado Precio unitario en U$S del pedido de venta. En los pedidos de Venta se indica el valor unitario de la pieza, por mas que se entregue en cajas. En este campo se Necesita obtener la sumatoria del producto entre Cantidad de piezas vendidas por la Relación de la unidad de medida en que se vendió la pieza por el precio unitario. Solo se mostrará información si la moneda es Dólares, caso contrario el campo debe figurar vacío.
- [x] **Facturación ARS** [invoiced_ars] 5ta Sumatoria por columna del Campo Calculado Precio unitario en Pesos del pedido de Venta. Aquí debe mostrarse la multiplicación entre la cantidad pedida por la relación de la unidad de medida del producto por el precio unitario. Este campo sólo mostrará información si la moneda es Pesos Argentinos, caso contrario deberá mostrarse vacío.

**Comment by jobiols** [comment]
[Despachada Vs. Vendida_1.6_sale.order_Amic.xlsx](https://github.com/jobiols/cl-amic/files/6539919/Despachada.Vs.Vendida_1.6_sale.order_Amic.xlsx)

Documentación en google docs
https://docs.google.com/document/d/1ttRcScwqdgT1uzTdG143m5W0Fh9eq6ow-5uEl4fTWXg/edit

**Comment by jobiols** [comment]
@sebatista se requiere ampliar info en 6to y 7mo agrupamiento

**Comment by sebatista** [comment]
El 6to agrupamiento, serían los números de remitos asociados a las transferencias relacionadas a un pedido, es decir, si el pedido SO051 tiene 26 transferencias, lo que armé en excel, es concatenar 0001-001231, 0001-001232, 0001-001244, ... y ésa concatenación la presenté junto al pedido de venta. Adjunto imagen ejemplificando.
![Acumulación de Remitos](https://user-images.githubusercontent.com/27778036/122104687-519baf00-cdee-11eb-8cd3-dd7f8503231f.png)

El 7mo agrupamiento, se puede visualizar en ésa captura, es simplemente mostrar las referencias internas de los productos involucrados en el pedido de venta o lo que es igual en la transferencias.

**Comment by jobiols** [comment]
@sebatista Sorry que tarde tanto en responder esto pero va una explicación.

En un pivot hay **Medidas** (que son cosas sumables) y **Dimensiones** que son cosas para seleccionar medidas o agrupar   medidas.
Por lo tanto no tiene sentido poner en una dimensión algo que es un dato que quieren ver.

Las dos ultimas agrupaciones mas bien tendrian que estar en un reporte no en el pivote.
