### ISSUE TITLE
valor erroneo en medida (?)

### ISSUE THREAD

**Issue by jobiols** [jobiols/cl-amic#146]
La relación de la unidad de medida. Nos referimos al valor que está en la pantalla de unidades de medida, que presenta cuántas unidades representa dicha unidad de medida. Actualmente se identificó en el filtro de la pantalla y en el botón de medidas, pero está mostrando un valor diferente al esperado.

**Comment by jobiols** [comment]
@sebatista favor identificar la medida según en nombre que se muestra en el botón MEDIDAS, indicar valor actual y valor correcto en un ejemplo reproducible de la bd produccion.

**Comment by sebatista** [comment]
La medida "UdM Relación" se está visualizando correctamete.
El valor esperado era el de la pantalla de unidades de medida el campo "Mayor Ratio", porque es lo que ayuda al usuario a entender si se vendieron 10 cajas de 220 (unidad de medida Cajas x 220) son 2200 unidades y validar rápidamente la cantidad de unidades o valoración de los campos calculados.
