### ISSUE TITLE
Crear o definir medida

### ISSUE THREAD

**Issue by jobiols** [jobiols/cl-amic#147]
El campo calculado de los Remitos acumulados (algo así como NroRemito1, NroRemito2, etc.) Explicado en detalle en la sección de campos calculados.

**Comment by jobiols** [comment]
@sebatista favor copiar aqui la descripcion detallada, no la encontré.
indicar nombre del campo, si ya existe o hay que crearlo.

**Comment by sebatista** [comment]
Este es el agrupamiento 7° que está en el otro Issue. Básicamente recopilo y concateno los remitos asociados a las transferencias relacionadas a un pedido. Entonces si un pedido tiene 10 transferencias y cada transferencia tienen el Remito1,etc le presento a Valeria el pedido y al lado (Remito1, Remito2, Remito3, Remito4, ....., Remito 10). Ver pantalla adjunta en el otro Issue.
