### ISSUE TITLE
Recibidas vs Compradas Campos Faltantes

### ISSUE THREAD

**Issue by jobiols** [jobiols/cl-amic#149]
- [x] Falta la fila **Prod. Referencia interna** [default_code]
- [x] Falta la fila Líneas del pedido/Precio unitario, ponerle el nombre Precio unitario en pesos, cuando la moneda es Pesos.
- [x] Falta la fila el Líneas del pedido/Precio unitario, ponerle el nombre Precio unitario en dólares, cuando la moneda es Dólares.
- [x] Falta la fila el Líneas del pedido/Precio unitario, ponerle el nombre Precio unitario en euros, cuando la moneda es Euros.
- [x] En medidas, falta el campo de nombre Costo recibido USD, que sería un campo calculado de la siguiente manera: Si la moneda es dolares, mostrar Campo "Líneas del pedido/Precio unitario" multiplicado por campo "Líneas del pedido/Ctdad recibida".
- [x] En medidas, falta el campo de nombre Costo recibido EUR, que sería un campo calculado de la siguiente manera: Si la moneda es Euros, mostrar campo  "Líneas del pedido/Precio unitario" multiplicado por campo "Líneas del pedido/Ctdad recibida".
- [x] En medidas, falta el campo de nombre Costo recibido ARS, que sería un campo calculado de la siguiente manera: Si la moneda es Pesos argentinos, mostrar campo  "Líneas del pedido/Precio unitario" multiplicado por campo "Líneas del pedido/Ctdad recibida".
- [x] Falta la **Almacen** [warehouse] que sería la planta donde se recibió el material, es decir "Líneas del pedido/Referencia del pedido/Entregar a".

**Comment by sebatista** [comment]
En el almacén que se visualiza en el signo + de las filas, aparecen valores extraños. Adjunto pantalla de los valores obtenidos del campo Líneas del pedido/Referencia del pedido/Entregar a mediante exportación y capturas de los datos obtenidos desde la tabla Pivot de Odoo.

![Excel Almacenes](https://user-images.githubusercontent.com/27778036/122137459-0f3c9700-ce1b-11eb-9745-b8ff8281829e.png)

![Odoo Almacenes](https://user-images.githubusercontent.com/27778036/122137522-309d8300-ce1b-11eb-9547-c2b957fef031.png)

**Comment by jobiols** [comment]
@sebatista podes revisar de nuevo si el almacen devuelve valores correctos?  Creo que lo arregle pero no marque el issue como resuelto.
Por otro lado los tres campos de costo que faltaban están listos.

**Comment by sebatista** [comment]
No se porque se duplicaron los issues, pero bueno sería lo que puse en el #160 .
