### ISSUE TITLE
Calidad - Carga de Issues/Inspecciones

### ISSUE THREAD

**Issue by marcellinoes** [jobiols/cl-amic#154]
En Control de Calidad > Issues > Issues > Abrir una tarjeta

Los campos **Inspector** y **Assigned to** deben poder seleccionar todos los empleados

![screenshot-amic arqytec com ar-2021 05 30-12_11_07](https://user-images.githubusercontent.com/8525908/120109609-7fbb9680-c140-11eb-944c-26474261c5b7.png)

**Comment by marcellinoes** [comment]
![image](https://user-images.githubusercontent.com/43271866/119700276-61485900-be29-11eb-920e-1c1f9b2cc191.png)
<Esto es Issues>

**Comment by marcellinoes** [comment]
![image](https://user-images.githubusercontent.com/43271866/119700697-ea5f9000-be29-11eb-9920-905061d11de5.png)

**Comment by jobiols** [comment]
@marcellinoes Que se supone que hago con eso que esta tachado en naranja.?

Al al darle al boton rojo que dice nonconformity aparece este formulario con el operador.
Donde es que no se pueden poner los operadores

![screenshot-localhost_8069-2021 05 26-16_06_50](https://user-images.githubusercontent.com/8525908/119717419-a7f37e80-be3c-11eb-8313-e0f19e9ef036.png)

**Comment by marcellinoes** [comment]
Pero no simpre van a usar el boton rojo... y si los formularios anterirores

**Comment by marcellinoes** [comment]
en lo naranja tienen que poder seleccionarse los operadores.. ahora solo se puede elegir usuario de odoo
