### ISSUE TITLE
Ruta del reporte en Odoo.

### ISSUE THREAD

**Issue by sebatista** [jobiols/cl-amic#157]
Ruta donde debe estar el reporte en Odoo: este reporte debe ser accedido por Valeria y personal responsable de fabricación. El reporte será dinámico, modificable mediante una tabla pivot de Odoo.

**Comment by jobiols** [comment]
La ruta la defini yo en Fabricacion >  Informes > Volumen y Kilogramos cortados

**Comment by sebatista** [comment]
Perfecto
