### ISSUE TITLE
Error? Actualización? modificaciones?

### ISSUE THREAD

**Issue by sebatista** [jobiols/cl-amic#163]
Hola Jorge. En éste informe aparecieron muchos campos que no se solicitaron y no hay campos que si se requieren (por ejemplo, referencia interna) Puede ser una actualización, que hayas modificado algo y se desconfiguró o algo así?

**Comment by jobiols** [comment]
@sebatista No hay errores los campos que hay son los que se muestran, pega aca la lista de campos requeridos por favor.
con sus nombres correctos. Hay veces que no esta claro que nombre ponerle al campo.

**Comment by sebatista** [comment]
Actualmente los campos en el signo mas y en medidas, permiten lograr el Reporte.
Cierro el Issue.
