### ISSUE TITLE
Error de Usuario al realizar Scrapt

### ISSUE THREAD

**Issue by sebatista** [jobiols/cl-amic#164]
Base de datos "amic_pre_prod_pruebas2" y en base de datos de producción.
Usuario "Silvana Mattes" silvana.mattes@amic.com.ar
Pantalla QC Issues, creando un nuevo scrapt desde la pantalla de issues. Pasa con todos los issues, pero se adjunta una captura de con un ejemplo.
Error que se genera
![WhatsApp Image 2021-05-12 at 1 24 17 PM](https://user-images.githubusercontent.com/27778036/120021254-309b2780-bfc1-11eb-97a6-b3452b247849.jpeg)

Desde que pantalla se llegó a la creación del scrapt.
![WhatsApp Image 2021-05-12 at 1 25 19 PM](https://user-images.githubusercontent.com/27778036/120021264-342eae80-bfc1-11eb-8dae-10ecddeff687.jpeg)

Para el mismo usuario en otras computadoras, puede no suceder el error.

**Comment by jobiols** [comment]
@marcellinoes @sebatista  Workaround para hacer scrap

https://user-images.githubusercontent.com/8525908/120118190-b0fb8d00-c167-11eb-9d7e-22616ef1b671.mp4
