### ISSUE TITLE
Boton de No Conformidad

### ISSUE THREAD

**Issue by marcellinoes** [jobiols/cl-amic#175]
Al querer grabar una No Conformidad, presionando el botón rojo, sale el siguiente error 

![Screenshot 2021-07-12 065306](https://user-images.githubusercontent.com/43271866/125268251-e73b3900-e2dd-11eb-8237-ec6b0f797e58.png)

**Comment by jobiols** [comment]
@marcellinoes  @sebatista  No puedo reproducir el problema

https://user-images.githubusercontent.com/8525908/125469522-38314325-04d7-4ba5-af38-e8d71165f0d4.mp4

**Comment by marcellinoes** [comment]
@jobiols  el problema es al querer grabar el formulario que aparece al presionar el botón rojo  no al abrir.. Es decir no funciona el Guardar una vez dentro de la noconformidad. Como dato desinstale la actualización que hiciste para que el formulario tenga unos campos agregados y el formulario original tiene un campo que ahora no esta y me parece que es el campo que esta dando error al querer guardar...

**Comment by jobiols** [comment]
@marcellinoes @sebatista ok ahora se entiende. ya lo arregle
