### ISSUE TITLE
columna OT en las transferencias de inventario

### ISSUE THREAD

**Issue by jobiols** [jobiols/cl-amic#82]
Cuando haya muchas transferencias de inventario no voy a saber cual es cual., seria bueno poner la ot en la vista de lista.

**Comment by jobiols** [comment]
No se puede poner la ot porque no hay relacion entre el modelo de picking y el de produccion, los movimientos se crean pero no se sabe que ot se esta moviendo hasta que se defina un lote.
Esto solo se podria hacer si hacemos el modelo OT #83

**Comment by marcellinoes** [comment]
Pero la MO si sale... no se puede relacionar por la MO?
